[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sglang_simulator"
dynamic = ["version"]
description = "A simulation benchmark tool for sglang"
dependencies = [
    "sglang==0.5.16",
    "numpy",
    "scikit-learn",
    "joblib",
]

[project.optional-dependencies]
aic = [
    "aiconfigurator @ git+https://github.com/ai-dynamo/aiconfigurator.git@c5f139662be28b177ca9f62f83543bbf10f133a0"
]
